[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.all]
dependencies = [
    "format",
    "build",
    "clippy",
    "test",
]