[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]
dependencies = ["build"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.all]
dependencies = [
    "fmt",
    "set-version",
    "build",
    "clippy",
    "test",
]

[tasks.set-version]
script_runner = "bash"
script = '''
    sed -i "s/{#RELEASE_VERSION}/${RELEASE_VERSION}/" src/cli_helpers.rs
'''

[tasks.install-local]
script_runner = "bash"
dependencies = ["release"]
script = '''
    mkdir -p ${DESTDIR}/usr/local/bin
    sudo cp target/release/kinesis-tailr ${DESTDIR}/usr/local/bin/
'''

[tasks.install]
script_runner = "bash"
dependencies = ["release"]
script = '''
    mkdir -p ${DESTDIR}/usr/bin
    cp target/release/kinesis-tailr ${DESTDIR}/usr/bin/
'''

[tasks.debian-pkg]
script_runner = "bash"
dependencies = ["install"]
script = '''
    mkdir -p ${DESTDIR}/DEBIAN
    cp build-aux/debian/control ${DESTDIR}/DEBIAN/
	echo "Version: ${RELEASE_VERSION}" >> ${DESTDIR}/DEBIAN/control
	cp build-aux/debian/postinst ${DESTDIR}/DEBIAN/
	chmod 775 ${DESTDIR}/DEBIAN/postinst
	dpkg-deb --build ${DESTDIR} kinesis-tailr-${RELEASE_VERSION}-x86_64.deb
	md5sum kinesis-tailr-${RELEASE_VERSION}-x86_64.deb > kinesis-tailr-${RELEASE_VERSION}-x86_64.deb.md5sum
'''
