[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.all]
dependencies = [
    "fmt",
    "build",
    "clippy",
    "test",
]