on:
  release:
    types:
      - created

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.69.0  # MSRV

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/release
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo \
            make

          mkdir -p ~/.cargo/release

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Create Debian package
        env:
          DESTDIR: '~/kinesis-tailr-deb'
        run: |
          mkdir -p $DESTDIR

      - name: Upload Debian release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb'
          asset_name: 'kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb'
          asset_content_type: application/octet-stream

      - name: Upload Debian release checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb.md5sum'
          asset_name: 'kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb.md5sum'
          asset_content_type: text/plain

#  arch:
#    runs-on: ubuntu-latest
#    needs: [ci]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Prepare arch package metadata
#        run: |
#          wget https://github.com/grumlimited/kinesis-tailr/releases/download/${{ github.event.release.tag_name }}/kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb -O build-aux/arch/kinesis-tailr-bin/kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb
#
#          MD5_SUM=$(md5sum build-aux/arch/kinesis-tailr-bin/kinesis-tailr-${{ github.event.release.tag_name }}-x86_64.deb  | awk '{print $1}')
#          awk -v q="'" -v MD5_SUM=$MD5_SUM -i inplace 'BEGINFILE{print "md5sums=(" q MD5_SUM q ")"}{print}' build-aux/arch/kinesis-tailr-bin/PKGBUILD
#          awk -i inplace 'BEGINFILE{print "pkgver=${{ github.event.release.tag_name }}"}{print}' build-aux/arch/kinesis-tailr-bin/PKGBUILD
#
#      - name: Validate PKGBUILD
#        id: validate-pkgbuild
#        uses: grumlimited/arch-pkgbuild-builder@b0f22da174699e6795f4434f252e15e6c8265b9e
#        with:
#          debug: true
#          target: pkgbuild
#          pkgname: build-aux/arch/kinesis-tailr-bin/
#
#      - name: Create arch package checksum file
#        run: |
#          sudo chown -R $USER .
#          md5sum build-aux/arch/kinesis-tailr-bin/*.zst >> build-aux/arch/kinesis-tailr-bin/kinesis-tailr-bin-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum
#
#      - name: Upload Arch Linux release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: '${{ github.event.release.upload_url }}'
#          asset_path: 'build-aux/arch/kinesis-tailr-bin/kinesis-tailr-bin-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
#          asset_name: 'kinesis-tailr-bin-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
#          asset_content_type: application/octet-stream
#
#      - name: Upload Arch Linux release checksum
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: '${{ github.event.release.upload_url }}'
#          asset_path: 'build-aux/arch/kinesis-tailr-bin/kinesis-tailr-bin-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum'
#          asset_name: 'kinesis-tailr-bin-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum'
#          asset_content_type: text/plain
