on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.70.0  # MSRV

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: davidB/rust-cargo-make@v1
      - uses: baptiste0928/cargo-install@v1

      - name: Formatting
        run: cargo make fmt

      - name: Clippy
        run: cargo make clippy

      - name: Build
        run: cargo make build

      - name: Tests
        run: cargo make test
        env:
          RUST_BACKTRACE: 1
